apiVersion: v1
kind: ServiceAccount
metadata:
  name: sidecar-injector-sa
  namespace: sidecar-injector
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sidecar-injector-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sidecar-injector-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sidecar-injector-role
subjects:
  - kind: ServiceAccount
    name: sidecar-injector-sa
    namespace: sidecar-injector
